name 'protected-fs'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures protected-fs'
long_description 'Installs/Configures protected-fs'
version '0.1.0'
